# Copyright 2021 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

apiVersion: skaffold/v3
kind: Config
metadata:
  name: gatekeeper-securitycenter
build:
  artifacts:
  - image: gatekeeper-securitycenter
    ko:
      dependencies:
        paths:
        - .ko.yaml
        - go.mod
        - '**/*.go'
        ignore:
        - '**/*_test.go'
  tagPolicy:
    inputDigest: {}
manifests:
  rawYaml:
  - manifests/*.yaml
profiles:
- name: release
  patches:
  - op: add
    path: /build/artifacts/0/ko/flags
    value:
    - -v
  - op: add
    path: /build/artifacts/0/ko/labels
    value:
      org.opencontainers.image.description: >-
        Report Policy Controller and OPA Gatekeeper audit violations in
        Security Command Center.
      org.opencontainers.image.licenses: Apache-2.0
      org.opencontainers.image.revision: '{{.REVISION}}'
      org.opencontainers.image.source: '{{.SOURCE}}'
      org.opencontainers.image.title: gatekeeper-securitycenter
      org.opencontainers.image.url: '{{.URL}}'
      org.opencontainers.image.vendor: Google LLC
      org.opencontainers.image.version: '{{.VERSION}}'
  - op: add
    path: /build/artifacts/0/ko/ldflags
    value:
    - -s
    - -w
  - op: add
    path: /build/artifacts/0/platforms
    value:
    - linux/amd64
    - linux/arm64
