# Copyright 2020 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

apiVersion: apps/v1
kind: Deployment
metadata:
  name: gatekeeper-securitycenter-controller-manager
  namespace: gatekeeper-securitycenter # {"$kpt-set":"namespace"}
spec:
  replicas: 1
  selector:
    matchLabels:
      control-plane: gatekeeper-securitycenter-controller-manager
  template:
    metadata:
      labels:
        control-plane: gatekeeper-securitycenter-controller-manager
      annotations:
        container.apparmor.security.beta.kubernetes.io/manager: runtime/default
        container.seccomp.security.alpha.kubernetes.io/manager: runtime/default
    spec:
      serviceAccountName: gatekeeper-securitycenter-controller
      containers:
      - name: manager
        image: gcr.io/cloud-solutions-images/gatekeeper-securitycenter:latest # {"$kpt-set":"image"}
        args:
        - findings
        - manager
        - --source=$(SOURCE)
        - --cluster=$(CLUSTER)
        env:
        - name: SOURCE
          valueFrom:
            configMapKeyRef:
              name: gatekeeper-securitycenter-config
              key: SOURCE_NAME
        - name: CLUSTER
          valueFrom:
            configMapKeyRef:
              name: gatekeeper-securitycenter-config
              key: CLUSTER_NAME
        - name: DEBUG
          value: "false"
        resources:
          limits:
            cpu: 100m
            memory: 128Mi
          requests:
            cpu: 30m
            memory: 32Mi
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - all
          readOnlyRootFilesystem: true
          runAsGroup: 65532
          runAsNonRoot: true
          runAsUser: 65532
