apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    control-plane: controller-manager
    gatekeeper-securitycenter/operation: manager
    gatekeeper-securitycenter/system: "yes"
  name: gatekeeper-securitycenter-controller-manager
  namespace: gatekeeper-securitycenter
spec:
  replicas: 1
  selector:
    matchLabels:
      control-plane: controller-manager
      gatekeeper-securitycenter/operation: controller
      gatekeeper-securitycenter/system: "yes"
  template:
    metadata:
      annotations:
        container.seccomp.security.alpha.kubernetes.io/manager: runtime/default
      labels:
        control-plane: controller-manager
        gatekeeper-securitycenter/operation: controller
        gatekeeper-securitycenter/system: "yes"
    spec:
      containers:
      - args:
        - findings
        - manager
        - --source=$(SOURCE)
        - --cluster=$(CLUSTER)
        - --interval=120
        - --dry-run=false
        env:
        - name: SOURCE
          valueFrom:
            configMapKeyRef:
              key: SOURCE_NAME
              name: gatekeeper-securitycenter-config
        - name: CLUSTER
          valueFrom:
            configMapKeyRef:
              key: CLUSTER_NAME
              name: gatekeeper-securitycenter-config
        - name: DEBUG
          value: "false"
        image: ghcr.io/googlecloudplatform/gatekeeper-securitycenter:v0.4.2@sha256:28883f0507487771513971512dcf3abddcc3aba705b9a0702e2e847abdd8f268
        name: manager
        resources:
          requests:
            cpu: 250m
            memory: 512Mi
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - all
          readOnlyRootFilesystem: true
          runAsGroup: 65532
          runAsNonRoot: true
          runAsUser: 65532
      serviceAccountName: gatekeeper-securitycenter-controller
